// src/modules/products/kxtill/services/export.service.js

import prisma from '../../../../database/postgres/prisma.js';
import PDFDocument from 'pdfkit';

const formatDate = (date) => {
  return new Date(date).toLocaleDateString('en-KE', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
};

const formatCurrency = (amount) => {
  return `KES ${Number(amount).toFixed(2)}`;
};

// ============================================================
// PDF GENERATION
// ============================================================

const generatePDF = (data, title) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 30, size: 'A4' });
      const chunks = [];

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));

      doc.fontSize(18).text(title, { align: 'center' });
      doc.moveDown();
      doc.fontSize(10).text(`Generated: ${new Date().toLocaleString()}`, { align: 'right' });
      doc.moveDown();

      if (!data || data.length === 0) {
        doc.fontSize(12).text('No data available');
        doc.end();
        return;
      }

      const headers = Object.keys(data[0]);
      const pageWidth = doc.page.width - 60;
      const colWidth = Math.min(80, pageWidth / headers.length);
      const tableWidth = headers.length * colWidth;
      const tableLeft = (doc.page.width - tableWidth) / 2;

      let rowY = doc.y + 10;

      doc.fontSize(9).font('Helvetica-Bold');
      headers.forEach((header, i) => {
        const x = tableLeft + i * colWidth;
        doc.text(header, x, rowY, { width: colWidth, align: 'left' });
      });

      doc.fontSize(8).font('Helvetica');
      rowY += 18;

      for (const row of data) {
        headers.forEach((header, i) => {
          const x = tableLeft + i * colWidth;
          const value = row[header] !== undefined && row[header] !== null ? String(row[header]) : '';
          doc.text(value, x, rowY, { width: colWidth, align: 'left' });
        });
        rowY += 16;

        if (rowY > doc.page.height - 40) {
          doc.addPage();
          rowY = 30;
          doc.fontSize(9).font('Helvetica-Bold');
          headers.forEach((header, i) => {
            const x = tableLeft + i * colWidth;
            doc.text(header, x, rowY, { width: colWidth, align: 'left' });
          });
          doc.fontSize(8).font('Helvetica');
          rowY += 18;
        }
      }

      doc.moveDown();
      doc.fontSize(8).text(`Generated by KXBYTE • ${new Date().toLocaleString()}`, {
        align: 'center',
        color: '#999999',
      });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

// ============================================================
// SALES EXPORT
// ============================================================

const exportSales = async (organizationId, startDate, endDate, branchId = null) => {
  const where = {
    organizationId,
    status: 'COMPLETED',
    createdAt: {
      gte: new Date(startDate),
      lte: new Date(endDate),
    },
  };

  if (branchId) {
    where.branchId = branchId;
  }

  const sales = await prisma.kxTillSale.findMany({
    where,
    include: {
      items: {
        include: {
          product: true,
        },
      },
      user: {
        select: {
          firstName: true,
          lastName: true,
        },
      },
      branch: {
        select: {
          name: true,
        },
      },
      payments: {
        select: {
          method: true,
        },
        take: 1,
      },
    },
    orderBy: { createdAt: 'desc' },
  });

  const flatData = [];
  for (const sale of sales) {
    for (const item of sale.items) {
      flatData.push({
        'Sale ID': sale.id.slice(0, 8).toUpperCase(),
        'Date': formatDate(sale.createdAt),
        'Time': new Date(sale.createdAt).toLocaleTimeString(),
        'Branch': sale.branch?.name || 'Main',
        'Attendant': `${sale.user?.firstName || ''} ${sale.user?.lastName || ''}`.trim(),
        'Product': item.product?.name || 'Unknown',
        'Quantity': Number(item.quantity),
        'Unit': item.unitAbbrev || '',
        'Unit Price': Number(item.unitPrice),
        'Total': Number(item.total),
        'Sale Total': Number(sale.totalAmount),
        'Payment Method': sale.payments?.[0]?.method || 'CASH',
      });
    }
  }

  return flatData;
};

// ============================================================
// STOCK EXPORT
// ============================================================

const exportStock = async (organizationId, branchId = null) => {
  const where = {
    organizationId,
    isActive: true,
  };

  const products = await prisma.kxTillProduct.findMany({
    where,
    include: {
      units: true,
      baseUnit: true,
      branchProducts: {
        where: branchId ? { branchId } : {},
        include: {
          branch: {
            select: { name: true },
          },
        },
      },
    },
    orderBy: { name: 'asc' },
  });

  const flatData = [];
  for (const product of products) {
    const branchStock = product.branchProducts.length > 0
      ? product.branchProducts
      : [{ stock: 0, minStock: 0, branch: { name: 'All Branches' } }];

    for (const bp of branchStock) {
      flatData.push({
        'Product': product.name,
        'SKU': product.sku || '-',
        'Category': product.category || '-',
        'Branch': bp.branch?.name || 'All',
        'Stock': Number(bp.stock),
        'Min Stock': Number(bp.minStock),
        'Status': bp.stock <= bp.minStock ? 'Low Stock' : 'OK',
        'Unit': product.baseUnit?.abbreviation || 'units',
      });
    }
  }

  return flatData;
};

// ============================================================
// TOP PRODUCTS EXPORT
// ============================================================

const exportTopProducts = async (organizationId, startDate, endDate, limit = 50) => {
  const takeLimit = typeof limit === 'string' ? parseInt(limit, 10) || 50 : limit || 50;

  const topProducts = await prisma.kxTillSaleItem.groupBy({
    by: ['productId'],
    where: {
      sale: {
        organizationId,
        status: 'COMPLETED',
        createdAt: {
          gte: new Date(startDate),
          lte: new Date(endDate),
        },
      },
    },
    _sum: {
      total: true,
      quantity: true,
    },
    orderBy: {
      _sum: {
        total: 'desc',
      },
    },
    take: takeLimit,
  });

  const productIds = topProducts.map((p) => p.productId);
  const products = await prisma.kxTillProduct.findMany({
    where: { id: { in: productIds } },
    select: {
      id: true,
      name: true,
      sku: true,
      category: true,
    },
  });

  const productMap = Object.fromEntries(products.map((p) => [p.id, p]));

  return topProducts.map((p) => {
    const product = productMap[p.productId];
    return {
      'Product': product?.name || 'Unknown',
      'SKU': product?.sku || '-',
      'Category': product?.category || '-',
      'Total Revenue': formatCurrency(p._sum.total || 0),
      'Quantity Sold': Number(p._sum.quantity || 0),
    };
  });
};

// ============================================================
// BRANCH PERFORMANCE EXPORT
// ============================================================

const exportBranchPerformance = async (organizationId, startDate, endDate) => {
  const branches = await prisma.branch.findMany({
    where: { organizationId, isActive: true },
    include: {
      sales: {
        where: {
          status: 'COMPLETED',
          createdAt: {
            gte: new Date(startDate),
            lte: new Date(endDate),
          },
        },
        select: {
          totalAmount: true,
          items: {
            select: {
              quantity: true,
            },
          },
        },
      },
    },
  });

  return branches.map((branch) => {
    const totalSales = branch.sales.reduce((sum, s) => sum + Number(s.totalAmount), 0);
    const totalItems = branch.sales.reduce((sum, s) => sum + s.items.reduce((acc, i) => acc + Number(i.quantity), 0), 0);
    const saleCount = branch.sales.length;

    return {
      'Branch': branch.name,
      'Total Sales': formatCurrency(totalSales),
      'Sale Count': saleCount,
      'Items Sold': totalItems,
      'Average Sale': saleCount > 0 ? formatCurrency(totalSales / saleCount) : formatCurrency(0),
    };
  });
};

// ============================================================
// TAX EXPORT
// ============================================================

const exportTax = async (organizationId, startDate, endDate) => {
  const sales = await prisma.kxTillSale.findMany({
    where: {
      organizationId,
      status: 'COMPLETED',
      createdAt: {
        gte: new Date(startDate),
        lte: new Date(endDate),
      },
    },
    include: {
      items: {
        include: {
          product: true,
        },
      },
      branch: {
        select: { name: true },
      },
    },
    orderBy: { createdAt: 'asc' },
  });

  const flatData = [];
  let totalTax = 0;

  for (const sale of sales) {
    for (const item of sale.items) {
      const tax = Number(item.taxAmount) || 0;
      totalTax += tax;
      flatData.push({
        'Date': formatDate(sale.createdAt),
        'Branch': sale.branch?.name || 'Main',
        'Product': item.product?.name || 'Unknown',
        'Quantity': Number(item.quantity),
        'Total': Number(item.total),
        'Tax Rate': `${Number(item.taxRate)}%`,
        'Tax Amount': tax,
      });
    }
  }

  return {
    items: flatData,
    summary: {
      'Total Tax Collected': formatCurrency(totalTax),
      'Total Sales': sales.length,
      'Total Items': flatData.length,
      'Period': `${formatDate(startDate)} - ${formatDate(endDate)}`,
    },
  };
};

// ============================================================
// AUDIT EXPORT
// ============================================================

const exportAudit = async (organizationId, startDate, endDate) => {
  const logs = await prisma.auditEvent.findMany({
    where: {
      organizationId,
      createdAt: {
        gte: new Date(startDate),
        lte: new Date(endDate),
      },
    },
    include: {
      user: {
        select: {
          firstName: true,
          lastName: true,
          email: true,
        },
      },
    },
    orderBy: { createdAt: 'desc' },
  });

  return logs.map((log) => ({
    'Date': formatDate(log.createdAt),
    'Time': new Date(log.createdAt).toLocaleTimeString(),
    'User': log.user ? `${log.user.firstName} ${log.user.lastName}`.trim() : 'System',
    'Email': log.user?.email || 'system@kxbyte.com',
    'Action': log.action.replace(/_/g, ' ').toLowerCase(),
    'Resource': log.resource || '-',
    'Resource ID': log.resourceId || '-',
    'Metadata': log.metadata ? JSON.stringify(log.metadata) : '-',
  }));
};

// ============================================================
// CSV GENERATION
// ============================================================

const generateCSV = (data) => {
  if (!data || data.length === 0) {
    return 'No data available';
  }

  const headers = Object.keys(data[0]);
  const rows = data.map((row) =>
    headers.map((header) => {
      const value = row[header] !== undefined && row[header] !== null ? row[header] : '';
      return typeof value === 'string' && (value.includes(',') || value.includes('"') || value.includes('\n'))
        ? `"${value.replace(/"/g, '""')}"`
        : value;
    })
  );

  return [headers.join(','), ...rows.map((row) => row.join(','))].join('\n');
};

// ============================================================
// EXPORTS
// ============================================================

export default {
  exportSales,
  exportStock,
  exportTopProducts,
  exportBranchPerformance,
  exportTax,
  exportAudit,
  generateCSV,
  generatePDF,
  formatCurrency,
  formatDate,
};